"""Generate a shareable, cited report from a discussion run.

A self-contained Markdown memo: synthesis + reviews, the project literature it
draws on (with DOIs), and (optionally) the verification verdicts — something you
can hand to a collaborator or paste into a paper's notes.
"""
from __future__ import annotations

from . import litdb, litstore


def _ref_list(task, k=6):
    """Relevant literature as (title, name, doi, score) — semantic if the DB is
    up, else the notes on file."""
    meta = {n["name"]: n for n in litstore.list_notes()}
    try:
        ok, _ = litdb.status()
        if ok and meta:
            hits = litdb.search(task, k=k)
            return [(h.get("title", h["name"]), h["name"],
                     meta.get(h["name"], {}).get("doi", ""), h["score"])
                    for h in hits]
    except Exception:
        pass
    return [(n.get("title", n["name"]), n["name"], n.get("doi", ""), None)
            for n in list(meta.values())[:k]]


def build_report(record, references=True, verify_text=None):
    crew = record.get("crew", "discussion")
    task = record.get("task", "")
    lines = [f"# Discussion report — {crew}", "",
             f"- **topology:** {record.get('topology')}",
             f"- **time:** {record.get('timestamp')}",
             f"- **task:** {task}", ""]

    outputs = record.get("outputs", [])
    mods = [o for o in outputs if o.get("kind") == "moderator" and o.get("ok", True)]
    revs = [o for o in outputs if o.get("kind") != "moderator" and o.get("ok", True)]

    if mods:
        lines += ["## Synthesis", "", mods[-1]["reply"], ""]
    if revs:
        lines += ["## Reviews", ""]
        for o in revs:
            lines += [f"### {o['agent']}  ({o['alias']}:{o['model']})", "",
                      o["reply"], ""]
    if verify_text:
        lines += ["## Verification — claims vs project evidence", "",
                  verify_text, ""]
    if references:
        lines += ["## References — relevant project literature", ""]
        refs = _ref_list(task)
        if not refs:
            lines.append("- (no literature notes on file)")
        for title, _name, doi, score in refs:
            extra = []
            if doi:
                extra.append(f"doi:{doi}")
            if score is not None:
                extra.append(f"relevance {score:.2f}")
            lines.append(f"- {title}" + (f"  — {' · '.join(extra)}" if extra else ""))
        lines.append("")
    lines.append("_Generated by MiniCrew._")
    return "\n".join(lines)
